<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Coworking Space_text-gray-400 bg-tra_6060b7</name>
   <tag></tag>
   <elementGuidId>36001da0-62a9-4095-b0f1-3cee34bda3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21b30d7c-ae61-471a-b348-9971b39dc6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>049e8287-40c9-4166-b9a6-c405c7e9df6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center ease-in-out delay-100</value>
      <webElementGuid>2f96f261-05c5-4a7e-9cb6-f4eecdb8041e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modal-toggle</name>
      <type>Main</type>
      <value>editUserModal</value>
      <webElementGuid>f496c6ef-5db9-4ceb-95b6-d911b0e40907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extralarge-modal&quot;)/div[@class=&quot;relative w-full max-w-lg h-full md:h-auto&quot;]/form[@class=&quot;relative bg-white rounded-tl-3xl rounded-bl-3xl shadow&quot;]/div[@class=&quot;p-3 mt-1 absolute rounded-t&quot;]/button[@class=&quot;text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center ease-in-out delay-100&quot;]</value>
      <webElementGuid>8bb63bea-71ee-4018-8cc7-4edf26e47e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>60e1b865-311f-4129-bccc-6e57e81ae247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='extralarge-modal']/div/form/div/button</value>
      <webElementGuid>a202200b-1c01-4812-beaa-336542239a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coworking Space'])[1]/following::button[2]</value>
      <webElementGuid>c5565589-dbf9-4616-b099-1d25a7ebcfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Suropati Space'])[1]/following::button[2]</value>
      <webElementGuid>d6dc3c5a-9cd8-4285-a2b5-1f1749af8745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Office'])[1]/preceding::button[1]</value>
      <webElementGuid>2ea1d767-4e88-4735-9991-3aa2becc9877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office ID'])[2]/preceding::button[1]</value>
      <webElementGuid>16f28c81-e388-4ac1-8dc9-528c566add7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>e75e8436-772f-42f9-9f4c-d9957948fed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>f7a964c9-0f0d-4c78-9406-2af990704a2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
