<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Coworking Space_p-3 mt-1 absolute rounded-t</name>
   <tag></tag>
   <elementGuidId>09062ac5-9ba7-410b-b491-bc70b63b4d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='extralarge-modal']/div/form/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-3.mt-1.absolute.rounded-t</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82f40ead-be48-40c6-9ed3-af4f45bb9627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-3 mt-1 absolute rounded-t</value>
      <webElementGuid>59e2fe8b-e91b-4385-b317-da46f2fa0b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extralarge-modal&quot;)/div[@class=&quot;relative w-full max-w-lg h-full md:h-auto&quot;]/form[@class=&quot;relative bg-white rounded-tl-3xl rounded-bl-3xl shadow&quot;]/div[@class=&quot;p-3 mt-1 absolute rounded-t&quot;]</value>
      <webElementGuid>48a0690d-a14b-46a7-9d41-c0622eb9f8a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='extralarge-modal']/div/form/div</value>
      <webElementGuid>89550637-1e60-4a1b-9be7-ea6d4ab61ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coworking Space'])[1]/following::div[4]</value>
      <webElementGuid>ed238454-b316-40e4-b76a-33afb7cc1758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Suropati Space'])[1]/following::div[4]</value>
      <webElementGuid>7e0963fc-46e3-45ef-a662-af73557b493e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Office'])[1]/preceding::div[1]</value>
      <webElementGuid>71561472-3a27-49f2-b6e3-e28a7d35f0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office ID'])[2]/preceding::div[1]</value>
      <webElementGuid>654f2ed0-27fb-4bc2-b285-7cbf779d50b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>9c191d35-d0bf-4f62-9eed-386e1e4e45ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
