<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save_accommodate</name>
   <tag></tag>
   <elementGuidId>d615d966-2ea2-4e80-845c-3ee867ac63cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='floating_outlined'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd3d1aa1-0559-40ea-aa11-9045aea6067e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b23babfd-23cb-4861-86fd-1cca23658cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>a1fdda87-37e1-45cd-9d05-14f6e38cb740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-400 block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>1ee0bbf4-c86f-4099-9fd8-317a6f462d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Accommodate</value>
      <webElementGuid>aee3d032-cd19-4948-a25c-ba3382a87a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accommodate</value>
      <webElementGuid>04c38e02-b1c3-40ab-9e75-3157d67632e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6a3cc780-8adf-41f0-a043-e417d76ec2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 ml-8 w-1/2&quot;]/div[@class=&quot;pb-6 w-full flex justify-between&quot;]/div[@class=&quot;w-3/4&quot;]/div[@class=&quot;relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>8f43f30c-e15d-460a-8be6-c2d596b2c61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86bbd1ae-b996-4dd0-8d60-860efe350e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4be8aa64-350e-4b68-8f17-a1873f62f0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>d1ce152d-34f3-4ad7-9264-02c4644aae30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-400 block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>b4c7006f-a7b9-4c7e-ba65-0ec2d2d8ae53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Accommodate</value>
      <webElementGuid>99bf1d09-301d-4552-b8f7-c10d15a14c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accommodate</value>
      <webElementGuid>b00df019-6237-462b-b9fa-e97781dbe7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d6c8e112-c635-4946-8462-4a1d9081040e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 ml-8 w-1/2&quot;]/div[@class=&quot;pb-6 w-full flex justify-between&quot;]/div[@class=&quot;w-3/4&quot;]/div[@class=&quot;relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>75d30f6d-51bb-463c-87f5-ffcaff42d10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>712c0528-f26c-4a7a-bda9-bb0b43b8102b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a9f2eec6-91aa-4b31-9ec9-daff00fa7938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>949f600c-97a2-4e39-ab72-5eda483f9098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-400 block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>ddf6ab08-5d1b-418c-948f-eca49ee7bb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Accommodate</value>
      <webElementGuid>6f167b5d-2982-437c-8530-575d8872a9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accommodate</value>
      <webElementGuid>9699fc9d-4197-4e12-b8b7-47658f16bc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a4ea3155-0ed2-4e0e-ae8e-78560d54c9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 ml-8 w-1/2&quot;]/div[@class=&quot;pb-6 w-full flex justify-between&quot;]/div[@class=&quot;w-3/4&quot;]/div[@class=&quot;relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>c2dfc674-d8f3-4cb0-8a67-54d202719d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='floating_outlined'])[11]</value>
      <webElementGuid>7648ee0c-388d-4c38-ab4a-1ed2a17c13ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>d951c5a6-fa01-4807-9db6-d1eb03d27d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>bcab4f6d-76c5-44be-bca3-b670906d4c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'floating_outlined' and @placeholder = 'Accommodate' and @name = 'accommodate']</value>
      <webElementGuid>1ba3a202-020d-4588-8768-ea8444a50dcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
