<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_lat</name>
   <tag></tag>
   <elementGuidId>bf6c848f-20da-4c8d-aff6-326459607982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='floating_outlined'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pb-6.w-full.flex.justify-between > div.w-full > div.relative > #floating_outlined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1320d8f5-d9b2-42bd-8516-4296570e172b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6661b6f-92c5-46e6-ae0e-e4d41e5db6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>77582765-f0ef-417b-a266-d9d03e26ea76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-400 block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>8ba68f25-52ca-4052-ac86-92ce4a1dab5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Latitude</value>
      <webElementGuid>11e52352-2896-4ba1-a53b-747aa04aa409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lat</value>
      <webElementGuid>516b5d20-6c32-4c14-8283-c1400309490d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>23007f76-5d4e-4893-bd67-f61616da5c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 mt-4 mb-4 w-1/2&quot;]/div[@class=&quot;pb-6 w-full flex justify-between&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>364907b7-1cd1-42ce-b820-263f80613d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71395444-6474-4f64-a1b6-55f9ef8c1945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bfab4de-e3d8-46c9-a5ff-11cb6b45a103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>684a2ae9-bc34-4de6-9d91-5f2bc50ae765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-400 block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>bb07f275-394b-453b-a3f4-0a7dd8e977e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Latitude</value>
      <webElementGuid>03293d34-fee6-400a-9459-9f129799200e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lat</value>
      <webElementGuid>17d59971-7f4b-480e-ac63-1cb9f834c9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1607d7d9-122c-4892-879a-794a84ac66e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 mt-4 mb-4 w-1/2&quot;]/div[@class=&quot;pb-6 w-full flex justify-between&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>94634c93-b6df-4645-af84-228bb8a0708e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f38c20e1-7a63-439b-ac6a-23532b07a2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c74944c8-1be8-4cda-a1bc-6d0dece7b7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>8255547a-fb18-4943-ac25-c1da63d83c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-400 block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>c3563b24-48e9-465f-8783-7268c5cebc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Latitude</value>
      <webElementGuid>107a0dfc-c141-4f24-923d-9defc60ed01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lat</value>
      <webElementGuid>7bd8cd96-d612-4135-ad78-632b49836594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d446bf10-5b0d-4e4c-a265-051823a5604c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 mt-4 mb-4 w-1/2&quot;]/div[@class=&quot;pb-6 w-full flex justify-between&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>fbbb4fcf-d136-433a-9b29-545133f98c78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='floating_outlined'])[9]</value>
      <webElementGuid>7386f0e1-4bdd-4b84-86a3-f1b34a7be078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div/form/div/div[10]/div/div/input</value>
      <webElementGuid>77ac9792-35ee-406f-8982-5203d0659c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/input</value>
      <webElementGuid>ac78cc73-eb9b-47a5-b9df-0bf8f1393d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'floating_outlined' and @placeholder = 'Latitude' and @name = 'lat']</value>
      <webElementGuid>c5eeb7b1-6452-4308-8b3e-a98eec43b6b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
