<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price(Rp)_inline-radio</name>
   <tag></tag>
   <elementGuidId>559a6022-801d-438a-9d93-5454730c37a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='inline-radio'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.mx-12 > #inline-radio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29d71793-da1a-4d58-8049-28bd83cba8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inline-radio</value>
      <webElementGuid>bb0c9812-5a67-4a97-802d-20117dec415e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a5da27dd-93cc-4b6c-8106-5f35b8835a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600</value>
      <webElementGuid>9ded1bcd-7bd3-4fa7-a6e2-bd85a2ccb681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>38cb18cf-a8b6-4b12-be31-c57210ac8c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 mt-4 mb-4 w-1/2&quot;]/div[@class=&quot;pb-6 flex w-full&quot;]/div[@class=&quot;flex mx-auto w-full ml-8&quot;]/div[@class=&quot;flex items-center mx-12&quot;]/input[@id=&quot;inline-radio&quot;]</value>
      <webElementGuid>229e8b32-0340-44f6-b670-c1b07b47941f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f697b115-6f0a-4e80-8d91-213d308dcd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inline-radio</value>
      <webElementGuid>cb8c29fc-daff-4aae-81c7-f768c21788f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d34f0e91-825f-48df-86d0-dd5f73c91518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600</value>
      <webElementGuid>0c52bcd2-684d-4291-95c6-b8c9d3ed0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>02b44f79-1694-49f2-9250-39eb1c63a0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl shadow w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 mt-4 mb-4 w-1/2&quot;]/div[@class=&quot;pb-6 flex w-full&quot;]/div[@class=&quot;flex mx-auto w-full ml-8&quot;]/div[@class=&quot;flex items-center mx-12&quot;]/input[@id=&quot;inline-radio&quot;]</value>
      <webElementGuid>3f17eae4-71f0-4ec1-bc3a-065b9198dd1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='inline-radio'])[2]</value>
      <webElementGuid>351aa5bd-559b-4ba9-8b9b-bfcdeed27917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div/form/div/div[4]/div[2]/div/input</value>
      <webElementGuid>a019ca6a-08b1-44d7-9f64-29d3b0f741e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>71568e37-d56c-4955-9108-b44079873bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inline-radio' and @type = 'radio']</value>
      <webElementGuid>c5151366-6bef-476c-8be2-7b571531539f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
