<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reset</name>
   <tag></tag>
   <elementGuidId>92767649-f19f-4082-b06d-5fdf9379ddf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='reset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb3e0f7f-b766-4cc0-9bb7-0bf2ea1f19c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>reset</value>
      <webElementGuid>955df99d-ba6d-4afe-8ab1-cb7bfa7f5d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-1/2 border-2 border-success rounded-lg text-success mr-8 hover:bg-success hover:text-white</value>
      <webElementGuid>20afade2-cd83-4d70-b9b2-c0ab75df8eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>3ee63634-1071-48d8-81ab-cd31a5282a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/div[@class=&quot;pb-8 pt-4&quot;]/div[@class=&quot;z-10&quot;]/div[@class=&quot;overflow-x-auto relative shadow-md sm:rounded-2xl&quot;]/table[@class=&quot;w-full text-sm text-left text-gray-500&quot;]/tbody[1]/tr[@class=&quot;bg-white border-b hover:bg-gray-50&quot;]/td[@class=&quot;py-4 px-6 flex gap-2 items-center justify-center&quot;]/div[@class=&quot;flex flex-row bg-black bg-opacity-30 overflow-y-scroll fixed left-0 top-0 z-50 justify-center items-center p-4 pt-32 w-full md:inset-0&quot;]/div[@class=&quot;bg-white rounded-2xl px-20 py-12 mt-96 mb-12 w-3/4 z-50 drop-shadow-4xl transform -translate-y-0 scale-25 transition-opacity transition-transform duration-300 center&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/form[@class=&quot;bg-white rounded-2xl drop-shadow-4xl w-full py-4 px-4 justify-between flex mt-8&quot;]/div[@class=&quot;mx-2 mt-4 mb-4 w-1/2&quot;]/div[@class=&quot;w-full flex justify-between&quot;]/button[@class=&quot;w-1/2 border-2 border-success rounded-lg text-success mr-8 hover:bg-success hover:text-white&quot;]</value>
      <webElementGuid>59d83ee6-9f07-48cb-8649-9bffb77d57d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='reset']</value>
      <webElementGuid>c0ff91bf-ca02-4816-9fa9-6f4a5e5630fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div[2]/div/div/table/tbody/tr[3]/td[8]/div/div/div/form/div/div[12]/button</value>
      <webElementGuid>541ce69b-24ad-466e-b655-0be363dce939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude'])[1]/following::button[1]</value>
      <webElementGuid>a1f3bb34-3574-49b7-843c-e0fe33a939cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latitude'])[1]/following::button[1]</value>
      <webElementGuid>b6c07b95-b9b1-4e7f-bf61-816c6400ef59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[1]</value>
      <webElementGuid>53fecd9f-6849-4d17-9dc5-f0cd32d55bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accommodate'])[1]/preceding::button[2]</value>
      <webElementGuid>b374b384-0bea-42d4-b25a-f421db05ccc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset']/parent::*</value>
      <webElementGuid>cd4f51f0-3b37-4646-b3e5-ccf18d3b611a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/button</value>
      <webElementGuid>835d908c-ac8d-45a5-80ee-6f9ae492572f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'reset' and (text() = 'Reset' or . = 'Reset')]</value>
      <webElementGuid>cb8a49e0-63de-4228-908c-835f73a5f909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
