<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_table-search-users</name>
   <tag></tag>
   <elementGuidId>fa634981-2c1f-4dfd-bce9-2038170a9695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table-search-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='table-search-users']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4185d84e-144a-4efa-90d5-1a9b69006254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c567baf5-c7e8-442c-9b1a-08d9b5b42dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table-search-users</value>
      <webElementGuid>183dc776-bf87-433c-824e-64161d8116f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500</value>
      <webElementGuid>1e184cfb-038c-4d87-974c-15328b91703f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for users</value>
      <webElementGuid>8868e8a8-a750-434d-9203-a5ae6538bf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-search-users&quot;)</value>
      <webElementGuid>f0282e84-9997-4bd9-b0e0-46ac5ffd0dfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='table-search-users']</value>
      <webElementGuid>26dd31d3-bc70-4768-8807-4ef9b453ee78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>889d8049-bebb-422f-93da-469ccfffe6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e4b45fd6-82a0-4ba0-b143-a06308079fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'table-search-users' and @placeholder = 'Search for users']</value>
      <webElementGuid>009077d1-a127-419a-95fb-84673ff81c6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
