<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_deergmail.com_32</name>
   <tag></tag>
   <elementGuidId>d5845962-46d5-4125-855a-44f7d3cbb837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='32']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e416c6c-3d8b-4545-824d-c405fb3746b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>6770b10d-04ca-4fc6-86ee-57ba3012684d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f1bbcc2-3233-4820-bdfb-074fc81db864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 </value>
      <webElementGuid>4fd716b5-b08b-4757-82a2-4e3cb82946b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>87f8ef84-ec19-41d2-a6f7-b8549c13972f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;32&quot;)</value>
      <webElementGuid>1bcebeec-30a6-430e-8233-a07e4f5db093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cb8fdbc-3bac-4717-9aa5-f2ca9570af8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>c03c1861-c442-49e9-8025-1ef56056dec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dcf99754-a798-43cc-9bc5-743e1be047f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 </value>
      <webElementGuid>31ad2c40-c4bc-48e1-8497-4855954d0f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>0a11dbb1-d86a-40e3-a072-a5a6c37adbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;32&quot;)</value>
      <webElementGuid>9d61763a-6e0d-48d5-8532-a8ef95c07384</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='32']</value>
      <webElementGuid>a1416677-77a8-4a97-9479-13f00e1c1be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div[2]/table/tbody/tr[5]/td/div/input</value>
      <webElementGuid>0264abbb-9ef9-4ace-91b1-46bfd6d7f52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/input</value>
      <webElementGuid>879ad90a-13a4-44a3-a74b-6b1c1bee9cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '32' and @type = 'checkbox']</value>
      <webElementGuid>469404c9-0e31-4c77-b7ef-e864b2ec4691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
