<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_table-search-users</name>
   <tag></tag>
   <elementGuidId>d7aaec68-a5f4-402a-b572-6af8aa740b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table-search-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='table-search-users']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a7316e1-682c-4043-9566-d06b63812777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b99ff99-b130-4e20-a80c-1047759ad30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table-search-users</value>
      <webElementGuid>95ad2b38-1523-4069-a00b-39e2f84bd676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500</value>
      <webElementGuid>2566575e-28b7-4848-a0ff-b2ac8f7e541b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for users</value>
      <webElementGuid>a04527eb-3eeb-486c-9a6b-c2dd948f2244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-search-users&quot;)</value>
      <webElementGuid>65491121-b948-4724-9840-97ad0c5c46ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='table-search-users']</value>
      <webElementGuid>00d05ea7-b1d5-469d-8992-06fafb2af970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>8df2c2b6-9f01-485f-8ada-354a4e1e027b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a6516223-3e4e-44cd-aa9d-ecc22c58e065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'table-search-users' and @placeholder = 'Search for users']</value>
      <webElementGuid>7f37bc29-c353-4b68-87ef-336675fceb98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
