<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_6</name>
   <tag></tag>
   <elementGuidId>77b35815-b2e2-49f1-bae3-9b5e27fec55c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9769db7-a408-4e43-9cc0-4f4fffa8c31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>13259b28-cfec-4abf-9cb8-fbaf573c32b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a2c10b45-9b56-4fbc-8c6c-0eb0a5aa5587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 </value>
      <webElementGuid>67bed957-51ba-4072-8e07-e8e5c3d21a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>331015a1-e6f3-4d87-a65a-7eba67921db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6&quot;)</value>
      <webElementGuid>78f380d0-5652-4525-8277-d680cfa143b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6']</value>
      <webElementGuid>c492967f-bd42-46fd-a0f3-e57b252e0f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/div[2]/table/tbody/tr/td/div/input</value>
      <webElementGuid>bdd6c55d-98cf-44e9-bae3-9f7486081533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>1f95dc48-9c8e-4447-888c-8467988da529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '6' and @type = 'checkbox']</value>
      <webElementGuid>4294e185-1cf8-44ee-ad5b-8b9bfa90bb09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
