<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>fbcea4d1-9953-4695-be45-38c9eac90e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b4a8898-932d-40a0-84e6-29450cda7280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2690081b-ab2b-4a37-a3db-f95bd19b3699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>0f056eb0-4df9-4880-a25c-58e893c52341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>48546ea8-ee4a-4130-afc7-4d9594217848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-1/2 flex justify-center content-center&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>783e7cd0-8f55-4518-8591-dc4e322c9990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50c07d1f-b376-4bef-a24d-543d81ee008a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a85f75c9-edd7-4d6c-8eaf-bb03707d71bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>6c7c2420-a4e9-4f73-a3fd-88dc9628e0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a3fae06e-984f-4919-8a4f-43be49de7feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-1/2 flex justify-center content-center&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>a6478481-80d9-4177-abfc-975db13385b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa1bd56b-a3d7-4f56-b075-eb61aeb86254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7f5d4d03-e730-48f5-94c5-726c90c30b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>a88bcd04-8ba4-48a1-b125-2f13b9b6b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3a826f47-6921-4ce9-9e8e-9a1dbc80988a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-1/2 flex justify-center content-center&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>de48c3df-34b7-4b29-b138-7b99ef4b955c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>24537bc9-1bb2-4707-8d96-dc1ed5b368cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div/div[2]/div/div/form/button</value>
      <webElementGuid>b691ed40-6a1d-46d8-aff0-2f9ff4e73359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset password'])[1]/following::button[1]</value>
      <webElementGuid>7853797f-1609-48e6-98f1-c0395617c64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>6f87228d-085e-4d53-9dce-beed2010abda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>7527d6dc-4fb2-4bcf-8529-989138b19244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>911b5cde-64d5-4e5c-b860-24a41afc5330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>a8ce189d-7be1-48f8-a266-03b900883964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
