<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>9eb7b395-9310-4d19-853e-77922b1eb493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b1a8e24-5ad5-4980-a8da-1d0b5bb9fb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>57cfe223-cfe8-45ce-8b09-af5dfdfe0437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>11e30195-85a7-4e55-acd5-c896911f86a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>ef86c583-c847-4d17-96f7-5af00b7e5c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>53954fd6-60b1-441c-a74f-df77a8cae925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76da9759-eeef-48c7-be28-b28948291ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>85a361c9-eaba-4bc4-9dfc-0ce5fdc5848d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>c1e279f1-60fb-4a33-b57e-0de83623e467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>185fcb7e-943f-4615-bdef-3889ddaca74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>4eb33f6f-2b38-43af-a4fb-8d5d7f8f5eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>719db5af-2331-43d2-b600-0ab4830ef971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2e072020-28a6-48ae-81ec-683ee060a834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>386fa05e-065f-4a70-87ed-63ea1f7b3e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3be7c15c-4280-4ec7-a806-01b60ab97f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>17672905-e9de-4d3e-a66a-6fb8d9c13e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>eb017a58-d07a-4a70-b1a8-1de60e4f5252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div/div[2]/div/form/button</value>
      <webElementGuid>27937abd-442e-4c4c-afc8-2668328f1157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password'])[1]/following::button[1]</value>
      <webElementGuid>d5c78138-6139-459e-8bac-40a54b2dcfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>8c847ac7-ed96-4390-a372-f8932af049f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>8a976619-a99c-48de-b29d-39251a10eb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7c6cdb88-8dd2-4194-84b5-afe07c33f690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>0490e5a0-9741-416b-b821-fb30cbf23fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
