<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BETTER SPACEWelcome Admin,Lets login to_78b365</name>
   <tag></tag>
   <elementGuidId>e14299f4-ae0f-401e-a9e7-ecedf86be481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>687db1c6-995a-4523-a722-2cbecdab4be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0</value>
      <webElementGuid>12ff7a31-2acd-4b28-9496-a6a0918b7220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BETTER SPACEWelcome Admin,Lets login to manage the appUsernamePasswordForgot your password?Forgot passwordLogin</value>
      <webElementGuid>d78c7e3b-1b1d-493e-9386-c15ffeea4795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0&quot;]</value>
      <webElementGuid>607ae0d5-21a3-45cf-b536-29920b0705bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div</value>
      <webElementGuid>c7023084-4d41-4fac-8f05-9a77390e0091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>b5ee9fa4-8da4-4166-b4b6-24d01cb3386b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BETTER SPACEWelcome Admin,Lets login to manage the appUsernamePasswordForgot your password?Forgot passwordLogin' or . = 'BETTER SPACEWelcome Admin,Lets login to manage the appUsernamePasswordForgot your password?Forgot passwordLogin')]</value>
      <webElementGuid>acc3a418-6a4e-428a-a24c-58dd856873c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
