<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Recent Status BookingDateNameTypeOffice_bf5ae8</name>
   <tag></tag>
   <elementGuidId>0692b5f5-ae06-4ebd-941b-5b1aea098bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/main/div[2]/div/div/section[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-6.space-y-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cab5d6b0-c078-46c2-ad61-581aa7481f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-6 space-y-6</value>
      <webElementGuid>77b5ff0d-5fed-4320-a813-bfc947e367aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recent Status BookingDateNameTypeOffice NamePrice(Rp)ActionApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAccept</value>
      <webElementGuid>59195e89-bda3-4e74-8fe3-bb8c39b67869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/section[@class=&quot;mt-10 flex flex-col bg-white rounded-3xl drop-shadow-4xl&quot;]/div[@class=&quot;p-6 space-y-6&quot;]</value>
      <webElementGuid>d29cc54c-eded-46b0-bedc-59334fcc968d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/section[2]/div</value>
      <webElementGuid>3caf896a-e207-46d2-8c18-7b677c85b825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Office'])[1]/following::div[2]</value>
      <webElementGuid>e756147e-e2eb-490d-afd7-8186e2bc35fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yearly'])[1]/following::div[4]</value>
      <webElementGuid>6f2f6689-3de3-417b-8e0b-709e83341f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div</value>
      <webElementGuid>aaef57ae-a6b3-4df7-80cb-159682a86451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Recent Status BookingDateNameTypeOffice NamePrice(Rp)ActionApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAccept' or . = 'Recent Status BookingDateNameTypeOffice NamePrice(Rp)ActionApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAcceptApple MacBook Pro 17&quot;SliverLaptop$2999LaptopRejectAccept')]</value>
      <webElementGuid>1487b56c-072a-4832-8a9d-e6b424a22d25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
