<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Transaction Chart12 - 18 Desember 2022W_cc97a8</name>
   <tag></tag>
   <elementGuidId>d80ca8b9-8659-4472-9e7a-1edce60a7fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/main/div[2]/div/div/section/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3ce849a-9958-4f89-b8c2-a103f30e7973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-8</value>
      <webElementGuid>1a0b4a0f-4dcd-4246-8068-b371ad858f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction Chart12 - 18 Desember 2022WeaklyMonthlyYearly</value>
      <webElementGuid>c907bd6d-4c65-490f-9184-dcae3043dede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bg-slate-50&quot;]/div[@class=&quot;flex&quot;]/main[1]/div[@class=&quot;flex content-center justify-center&quot;]/div[@class=&quot;pl-80 duration-500 pt-20 flex justify-center w-screen&quot;]/div[@class=&quot;p-12 bg-slate-50 mb-4 container text-black w-full&quot;]/section[@class=&quot;flex gap-4 mt-10&quot;]/div[@class=&quot;w-1/2 bg-white rounded-xl drop-shadow-4xl&quot;]/div[@class=&quot;p-8&quot;]</value>
      <webElementGuid>99c787e1-9fda-4783-95b1-5d5ede101eb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div[2]/div/div/section/div/div</value>
      <webElementGuid>63215a52-152d-4db0-b06e-806ddfd5f8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>cd2909ba-cb23-4b20-9a4c-0bd42eb1a332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Transaction Chart12 - 18 Desember 2022WeaklyMonthlyYearly' or . = 'Transaction Chart12 - 18 Desember 2022WeaklyMonthlyYearly')]</value>
      <webElementGuid>b7c62209-30b4-4786-9b99-27d18e266414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
