<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>5140e2a1-0dcd-4209-922f-201340f52298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26a89aeb-0952-49be-b9f0-babe5221a176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c0e0503a-da7e-45d3-92a4-bb69f9045055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>ab1d59b2-7751-4a86-8387-37cee51c1448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>11fa1af7-abbb-47e3-9118-e1861c68bb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-1/2 flex justify-center content-center&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>6e56c3f0-caa6-4557-afc7-1a951a9ebee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3aef9ea3-1612-4f61-be76-222065d6d3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3ecd5455-4162-4814-8e65-5c5c91f3ace0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>f46771f9-7d76-4bac-9767-b08e750f3cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3fb614d4-e21d-4aef-b278-726499574044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-1/2 flex justify-center content-center&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>352b5bc5-e6b2-4f64-9989-e7c83356a4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>103e63b0-0074-48b7-82e7-5ac64ddc4753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6ea38980-c29d-4904-ad22-8788b6c33b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>33b57567-11bd-45b6-9897-8b86eeea7780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>77021485-4eb3-4275-ac04-ca4fc0213667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-1/2 flex justify-center content-center&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>e7aafb03-a8a3-4b0e-85ee-5c7435dc425f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a69a204-881f-490a-81bf-61153676c397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bae0bb79-18bc-45e5-ad61-f729736e73ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center</value>
      <webElementGuid>2942d527-6200-41d0-b82d-4b1da728f167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>f75ac157-2042-46b4-af9f-8b345bb25eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex items-center justify-center py-8 mx-auto md:h-screen lg:py-0&quot;]/div[@class=&quot;w-1/2 flex justify-center content-center&quot;]/div[@class=&quot;w-full bg-white rounded-2xl custom shadow-dark md:mt-0 sm:max-w-md xl:p-0&quot;]/div[@class=&quot;p-6 space-y-2 md:space-y-4 sm:p-8&quot;]/form[@class=&quot;space-y-4 pt-4&quot;]/button[@class=&quot;w-full text-white bg-secondary hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>5d26c053-9d34-47b2-ab1a-ce6a9adea9b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>51173bd1-b647-41a9-8d99-9742e282b933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div/div[2]/div/div/form/button</value>
      <webElementGuid>7b63b409-55fe-4147-af3a-6637baff2165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset password'])[1]/following::button[1]</value>
      <webElementGuid>c3e5f1e6-467d-4933-8854-2dfe72f15e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>3ee4ed6f-ac22-4bce-b614-ddc10c126c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>09670871-67a0-4511-aefe-9b41bc6dce33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>525ced50-ff54-47a4-8817-21357e74af45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>9edb7eed-3896-422d-bc8b-f785cb4e2970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
