<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_type</name>
   <tag></tag>
   <elementGuidId>c198a786-beca-402b-b7b2-2b9f89db95f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='floating_outlined'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>662f623b-5123-403b-85cf-92929e99aa06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97903405-7c7c-4262-a7b0-9ef7e05d9e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>03ba68f8-8464-4e2d-9564-57fda6785fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>175287c4-1b97-4e3d-8abf-701f39634145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>632f617b-ef5c-4e34-8524-2ab8f48d2600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>b22c6bea-44f0-4446-a682-ec1c3805fac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5281328-644a-4267-a27e-f561935ce3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>coworking space</value>
      <webElementGuid>3477e324-057c-4dd4-8f0b-d447d721ebb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editUserModal&quot;)/div[@class=&quot;relative w-full max-w-lg h-full md:h-auto&quot;]/div[@class=&quot;relative bg-white pb-6 rounded-lg shadow&quot;]/form[@class=&quot;py-2 px-6 space-y-6&quot;]/div[@class=&quot;px-6 lg:px-8 space-y-4&quot;]/div[@class=&quot;undefined relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>40531900-95d2-49ed-ad86-7bb015594a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='floating_outlined'])[2]</value>
      <webElementGuid>e9d44722-56b9-484e-9f2e-c2c54c05ebb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editUserModal']/div/div/form/div/div[3]/input</value>
      <webElementGuid>8086348d-891a-4270-95fc-6a8d3b7d4daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>12db2cfb-aa41-4e3b-8b0e-113e3828cdd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'floating_outlined' and @placeholder = 'Type' and @name = 'type']</value>
      <webElementGuid>5c4c7c6c-4670-4af7-abf1-f8a548367971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
