<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_status</name>
   <tag></tag>
   <elementGuidId>5d3c90b7-c7fa-46c3-9d17-5ac4707a15d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='floating_outlined'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>879d255b-7b45-4f18-971d-1326dbf958dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cd05ad0-e05b-4c0e-bcba-42ee03eda037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>7f5f8f20-430d-4f1b-90a2-689c23d02358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>5759446e-bd69-4393-9d63-fd4eaa19dd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>0d29940a-acd8-4bae-9a35-100b34dec58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>f5f31238-cf53-41fb-ba3f-1bd8665a4eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f66538aa-1a32-46ec-bcd0-7441d4e78c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pending</value>
      <webElementGuid>3fbd0d16-0617-4bfa-93db-caf2f42d4abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editUserModal&quot;)/div[@class=&quot;relative w-full max-w-lg h-full md:h-auto&quot;]/div[@class=&quot;relative bg-white pb-6 rounded-lg shadow&quot;]/form[@class=&quot;py-2 px-6 space-y-6&quot;]/div[@class=&quot;px-6 lg:px-8 space-y-4&quot;]/div[@class=&quot;undefined relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>eeaac713-e3df-429a-85c5-bc336b4a7519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='floating_outlined'])[4]</value>
      <webElementGuid>a707fa9c-d44d-41cd-a77a-4f9618cac139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editUserModal']/div/div/form/div/div[5]/input</value>
      <webElementGuid>4a28a977-7935-49d9-9448-e8c55f9ea574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>71dc404a-99c3-44e3-947d-985a247ac189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'floating_outlined' and @placeholder = 'Status' and @name = 'status']</value>
      <webElementGuid>87c00042-0055-426d-bdd8-864278de307a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
