<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Transaction_full_name</name>
   <tag></tag>
   <elementGuidId>e154a037-40ad-4d6b-adcb-001180d8f585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_outlined']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#floating_outlined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f934a8e2-773d-4f13-b0ee-f24629693921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>582a40a5-af34-4ab4-b868-37d31df3c341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined</value>
      <webElementGuid>8dca8ed1-33a8-4a25-ae77-e21763b08803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>2a8a2b63-da42-4ca0-ab80-40847a92fb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full Name</value>
      <webElementGuid>a68ee9dd-286e-41ad-9cf8-af9ea3be11b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>6d01cbfe-e565-489a-8b3e-85e98c85f8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1eeedf57-e6dc-49f6-ac12-76fb3f4fb6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Selena 12</value>
      <webElementGuid>5f1b2127-5335-4fc1-a4bb-9375e324996a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editUserModal&quot;)/div[@class=&quot;relative w-full max-w-lg h-full md:h-auto&quot;]/div[@class=&quot;relative bg-white pb-6 rounded-lg shadow&quot;]/form[@class=&quot;py-2 px-6 space-y-6&quot;]/div[@class=&quot;px-6 lg:px-8 space-y-4&quot;]/div[@class=&quot;undefined relative&quot;]/input[@id=&quot;floating_outlined&quot;]</value>
      <webElementGuid>52d25576-9758-4aae-9de1-483f16f829b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_outlined']</value>
      <webElementGuid>fd5cbc4f-5455-4e21-8353-bb586d95d706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editUserModal']/div/div/form/div/div[2]/input</value>
      <webElementGuid>99fef78f-8284-470f-a764-e90d835f9ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>aa82ec5b-5ed3-4c13-b6ae-bf3503d31944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'floating_outlined' and @placeholder = 'Full Name' and @name = 'full_name']</value>
      <webElementGuid>0a38ed3d-a563-4341-bb2d-1c003bcf7bf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
